apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    blueGreen: 
      # Using explicit names to avoid any template mismatch
      activeService: frontend
      previewService: frontend-preview
      autoPromotionEnabled: false 
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
            - containerPort: {{ .Values.service.port }}


